### ISSUE TITLE
AKStreamKeeper.dll启动报错

### ISSUE THREAD

**Issue by cuixiren** [chatop2020/AKStream#44]
[root@VM-16-14-centos AKStreamKeeper]# dotnet AKStreamKeeper.dll
2022-01-18 10:33:44,045 [1] INFO  AKStream - [AKStreamKeeper]->Let's Go...
Unhandled exception. LibCommon.AkStreamException: Exception of type 'LibCommon.AkStreamException' was thrown.
   at AKStreamKeeper.MediaServerInstance..ctor(String binPath, AKStreamKeeperConfig keeperConfig, String configPath) in /AKStream/AKStreamKeeper/MediaServerInstance.cs:line 88
   at AKStreamKeeper.Common.StartupMediaServer() in /AKStream/AKStreamKeeper/Common.cs:line 117
   at AKStreamKeeper.Common.Init() in /AKStream/AKStreamKeeper/Common.cs:line 739
   at AKStreamKeeper.Program.Main(String[] args) in /AKStream/AKStreamKeeper/Program.cs:line 15
Aborted (core dumped)

通过 http://公网ip/index/api/setServerConfig?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&hook.enable=0 接口修改config.ini文件配置，想关掉推流和播放的鉴权。停止服务后重新启动报错。

**Comment by cuixiren** [comment]
排查原因是调setServerConfig接口时config.ini文件头部被加了代码，dotnet AKStreamWeb.dll执行时读取失败了。但是通过./MediaServer生成的config.ini在启动keeper时会被还原掉，OBS提示无法推流，这个有什么解决办法吗？

**Comment by chatop2020** [comment]
config.ini文件中的内容确实会被akstreamkeeper替换的，这个是程序机制，如果你是obs的推流的问题，可以自己修改代码来支持直播推流，另外，可以加群交流

**Comment by cuixiren** [comment]
> config.ini文件中的内容确实会被akstreamkeeper替换的，这个是程序机制，如果你是obs的推流的问题，可以自己修改代码来支持直播推流，另外，可以加群交流

感谢回复，已入群
