### ISSUE TITLE
MediaServer/WebHook/OnPlay:数组的偏移量和长度超出了界限，或者计数大于从索引到源集合末尾的元素数量。

### ISSUE THREAD

**Issue by jiechengyang** [chatop2020/AKStream#51]
2022-06-22 13:41:04,780 [.NET ThreadPool Worker] ERROR AKStream - [AKStreamWeb]->HTTP-OUTPUT->::ffff:192.168.10.1->POST->/MediaServer/WebHook/OnPlay->StatusCode:500->Body: 抱歉，出错了
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at LiteDB.Engine.BufferReader.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LiteDB.Engine.BufferReader.ReadNumber[T](Func`3 convert, Int32 size)
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadArray()
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.BasePipe.LoadDocument(IEnumerable`1 nodes)+MoveNext()
   at LiteDB.Engine.BasePipe.Filter(IEnumerable`1 source, BsonExpression expr)+MoveNext()
   at LiteDB.Engine.BasePipe.Filter(IEnumerable`1 source, BsonExpression expr)+MoveNext()
   at LiteDB.Engine.QueryPipe.Select(IEnumerable`1 source, BsonExpression select)+MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at AKStreamWeb.Services.WebHookService.OnPlay(ReqForWebHookOnPlay req)
   at lambda_method1377(Closure , Object , Object[] )

**Comment by chatop2020** [comment]
光是这个报错没办法排查，请提供运行环境，发生问题的场景等内容

**Comment by jiechengyang** [comment]
sorry，大佬大大
运行环境：
ubuntu server 20.0.4  内存 62 g 带宽上下行：100m
![image](https://user-images.githubusercontent.com/33148475/175853383-ef71c788-8389-447d-979b-61e97013268e.png)
系统运行情况：
 目前系统运行了3个月了，里面有28个摄像头，在线的有10多个，然后有一个摄像头是自动推流，一直直播。其它都是按需直播。在我提问题的那天中午，突然有人反馈监控看不了了，当时再看的视频只有那个一直直播的摄像头（估计有好几个地方再看），然后我查看日志就是上面提到的错误，最后我就重启两个服务就好了

**Comment by chatop2020** [comment]
从日志来看，发生在onplay的位置 ，理论上，如果只有这里报错，并不影响程序继续运行，可能还有其他情况，日志没有表现出来，继续观察一下，看是否可以找到更精准的问题所在。

**Comment by jiechengyang** [comment]
感谢大大，我这边在观察下。在群里也看了，我也试着把liteDb换成mongodb，我们后期业务会扩大

**Comment by chatop2020** [comment]
那我就关掉了哦
