### ISSUE TITLE
docker运行web容器失败

### ISSUE THREAD

**Issue by xsir99** [chatop2020/AKStream#69]
使用 deploy.sh 打包 docker镜像，启动 web 容器的时候启动失败， 报以下错误
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'LibSystemInfo.CPULinuxLoadValue' threw an exception.
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/bin/top' with working directory '/app'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at LibCommon.ProcessHelper.RunProcess(String StartFileName, String StartFileArg) in /src/LibCommon/ProcessHelper.cs:line 169
   at LibSystemInfo.CPULinuxLoadValue..cctor() in /src/LibSystemInfo/CPULinuxLoadValue.cs:line 19
   --- End of inner exception stack trace ---
   at LibSystemInfo.SystemInfo.GetInfo() in /src/LibSystemInfo/SystemInfo.cs:line 109
   at System.Threading.Thread.StartCallback()
/bin/bash: line 1: free: command not found
Unhandled exception. System.TypeInitializationException: The type initializer for 'LibSystemInfo.CPULinuxLoadValue' threw an exception.
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/bin/top' with working directory '/app'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at LibCommon.ProcessHelper.RunProcess(String StartFileName, String StartFileArg) in /src/LibCommon/ProcessHelper.cs:line 169
   at LibSystemInfo.CPULinuxLoadValue..cctor() in /src/LibSystemInfo/CPULinuxLoadValue.cs:line 19
   --- End of inner exception stack trace ---
   at LibSystemInfo.SystemInfo.GetInfo() in /src/LibSystemInfo/SystemInfo.cs:line 109
   at System.Threading.Thread.StartCallback()
```

**Comment by chatop2020** [comment]
这是网友pr我合并的，请作者来看看是什么情况
从报错来看，是系统里缺少/usr/bin/top 命令导致性能无法采集

**Comment by m-coder-stack** [comment]
镜像的问题，dotnet镜像缺top、route和ifconfig，我推了个修改

**Comment by chatop2020** [comment]
> 镜像的问题，dotnet镜像缺top、route和ifconfig，我推了个修改

你提一个pr好了

**Comment by chatop2020** [comment]
pr已合并，感谢支持，这个issus关掉了
