### ISSUE TITLE
Ubuntu 22运行AKStreamWeb报错

### ISSUE THREAD

**Issue by xujiake** [chatop2020/AKStream#78]
Ubuntu 22.04.3 LTS，运行 `dotnet /root/AKStreamWeb/AKStreamWeb.dll`
报错信息：
```
Unhandled exception. System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_TotalSize()
   at LibSystemInfo.DiskInfoValue.GetDrivesInfo() in /opt/AKStream/LibSystemInfo/DiskInfoValue.cs:line 20
   at LibSystemInfo.SystemInfo.GetInfo() in /opt/AKStream/LibSystemInfo/SystemInfo.cs:line 95
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)
```

**Comment by chatop2020** [comment]
应该是系统层面的问题，这个我没办法解决
