### ISSUE TITLE
使用deploy部署的程序报错。

### ISSUE THREAD

**Issue by BobDLA** [chatop2020/AKStream#86]
看着zlm启动了， 然后keeper还在访问问题吧？这个咋弄呢...

报错日志如下
2024-05-17 16:46:19,645 [16] ERROR AKStream - [JsonHelper]->Json返序列化异常->Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.UInt16]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Code', line 1, position 8.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at LibCommon.JsonHelper.FromJson[T](String json, MissingMemberHandling p) in /root/src/LibCommon/JsonHelper.cs:line 187
json内容：{"Code":"Sys_HttpClientTimeout","Message":"http客户端请求超时或服务不可达"}
2024-05-17 16:46:19,645 [16] DEBUG AKStream - [AKStreamKeeper]->获取在用Rtp端口列表->null
2024-05-17 16:46:20,373 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...

2024-05-17 16:46:59,656 [16] ERROR AKStream - [JsonHelper]->Json返序列化异常->Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.UInt16]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Code', line 1, position 8.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at LibCommon.JsonHelper.FromJson[T](String json, MissingMemberHandling p) in /root/src/LibCommon/JsonHelper.cs:line 187
json内容：{"Code":"Sys_AKStreamKeeperNotRunning","Message":"AKStreamKeeper流媒体服务器治理程序没有运行"}
2024-05-17 16:46:59,656 [16] DEBUG AKStream - [AKStreamKeeper]->获取在用Rtp端口列表->null
2024-05-17 16:47:00,373 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(461)
2024-05-17 16:47:01,372 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(462)
2024-05-17 16:47:02,375 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(463)
2024-05-17 16:47:03,374 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(464)
2024-05-17 16:47:04,373 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(465)
2024-05-17 16:47:04,376 [33] INFO  AKStream - [AKStreamKeeper]->控制服务器反馈，要求重启流媒体服务器,马上重启
2024-05-17 16:47:04,377 [33] INFO  AKStream - [AKStreamKeeper]->终止流媒体服务器运行->False
2024-05-17 16:47:04,677 [33] INFO  AKStream - [AKStreamKeeper]->启动流媒体服务器成功->282
2024-05-17 16:47:04,681 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.681 I MediaServer[282-MediaServer] System.cpp:135 systemSetup | core文件大小设置为:18446744073709551615
2024-05-17 16:47:04,681 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.681 I MediaServer[282-MediaServer] System.cpp:144 systemSetup | 文件最大描述符个数设置为:1048576
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.681 D MediaServer[282-stamp thread] util.cpp:364 operator() | Stamp thread started!
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] EventPoller.cpp:460 EventPollerPool | 创建EventPoller个数:6
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:554
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:1935
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:80
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:443
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:9000
2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:10000
2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] UdpServer.cpp:104 start_l | UDP Server bind to [::]:10000
2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] UdpServer.cpp:104 start_l | UDP Server bind to [::]:9000
2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] main.cpp:361 start_main | 已启动http api 接口
2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] main.cpp:363 start_main | 已启动http hook 接口
2024-05-17 16:47:05,373 [41] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(466)
2024-05-17 16:47:06,373 [41] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(467)
2024-05-17 16:47:07,372 [41] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(468)
2024-05-17 16:47:08,374 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(469)
2024-05-17 16:47:09,373 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(470)

配置文件 AKStreamKeeper/Config/AKStreamKeeper.json
{
  "IpV4Address": "127.0.0.1",
  "IpV6Address": "fe80::8:807:2143:28a1%5",
  "Candidate":"127.0.0.1",
  "WebApiPort": 6880,
  "MediaServerPath": "/opt/media/MediaServer",
  "AkStreamWebRegisterUrl": "http://172.17.0.1:5800/MediaServer/WebHook/MediaServerKeepAlive",
  "CutMergeFilePath": "/Users/qiuzhouwei/Downloads/CutMergeFile",
  "CustomRecordPathList": [
    "/Users/qiuzhouwei/Downloads"
  ],
  "UseSsl": false,
  "MinRtpPort": 10001,
  "MaxRtpPort": 20000,
  "MinSendRtpPort": 20002,
  "MaxSendRtpPort": 20200,
  "RandomPort": false,
  "FFmpegPath": "/usr/bin/ffmpeg",
  "AccessKey": "047I4WS1-U51UBO6W-1J4BT21P-MF17IT99-92J8WIHU-944Q4KIW",
  "RtpPortCdTime": 3600,
  "HttpClientTimeoutSec": 5,
  "DisableShell": false,
  "CheckLinuxDiskMount": false,
  "ZLMediakitSSLFilePath": "./sslfiles/",
  "ListenIp": "0.0.0.0",
  "EnableRtspAuth": true
}

配置文件 AKStreamWeb/Config/AKStreamWeb.json

{
  "MediaServerFirstToRestart": true,
  "DbType": "MySql",
  "OrmConnStr": "Data Source=172.17.0.1;Port=3306;User ID=root;Password=pianote; Initial Catalog=akstream;Charset=utf8; SslMode=none;Min pool size=1;",
  "WebApiPort": 5800,
  "AccessKey": "047I4WS1-U51UBO6W-1J4BT21P-MF17IT99-92J8WIHU-944Q4KIW",
  "HttpClientTimeoutSec": 5,
  "WaitEventTimeOutMSec" : 10000,
  "WaitSipRequestTimeOutMSec" : 5000,
  "DeletedRecordsExpiredDays" : 30,
  "EnableGB28181Server": true,
  "EnableGB28181Client": false,
  "ZlmFlvPrefix" : "live",
  "ListenIp": "0.0.0.0",
  "ForwardUnmanagedRtmpRtspRtcStream": false,
  "LocalizationKingBaseDb": false,
  "ForwardUrlIn": "http://",
  "ForwardUrlOut": "http://",
  "ForwardUrlOnRecord": "http://",
  "PushStreamIpGetUrl": ""
}

**Comment by chatop2020** [comment]
还是访问不通造成的，你自己再查查原因吧

**Comment by SCUT-chenjia** [comment]
> 看着zlm启动了， 然后keeper还在访问问题吧？这个咋弄呢...
> 
> 报错日志如下 2024-05-17 16:46:19,645 [16] ERROR AKStream - [JsonHelper]->Json返序列化异常->Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.UInt16]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'Code', line 1, position 8. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at LibCommon.JsonHelper.FromJson[T](String json, MissingMemberHandling p) in /root/src/LibCommon/JsonHelper.cs:line 187 json内容：{"Code":"Sys_HttpClientTimeout","Message":"http客户端请求超时或服务不可达"} 2024-05-17 16:46:19,645 [16] DEBUG AKStream - [AKStreamKeeper]->获取在用Rtp端口列表->null 2024-05-17 16:46:20,373 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...
> 
> 2024-05-17 16:46:59,656 [16] ERROR AKStream - [JsonHelper]->Json返序列化异常->Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.UInt16]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'Code', line 1, position 8. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at LibCommon.JsonHelper.FromJson[T](String json, MissingMemberHandling p) in /root/src/LibCommon/JsonHelper.cs:line 187 json内容：{"Code":"Sys_AKStreamKeeperNotRunning","Message":"AKStreamKeeper流媒体服务器治理程序没有运行"} 2024-05-17 16:46:59,656 [16] DEBUG AKStream - [AKStreamKeeper]->获取在用Rtp端口列表->null 2024-05-17 16:47:00,373 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(461) 2024-05-17 16:47:01,372 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(462) 2024-05-17 16:47:02,375 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(463) 2024-05-17 16:47:03,374 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(464) 2024-05-17 16:47:04,373 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(465) 2024-05-17 16:47:04,376 [33] INFO AKStream - [AKStreamKeeper]->控制服务器反馈，要求重启流媒体服务器,马上重启 2024-05-17 16:47:04,377 [33] INFO AKStream - [AKStreamKeeper]->终止流媒体服务器运行->False 2024-05-17 16:47:04,677 [33] INFO AKStream - [AKStreamKeeper]->启动流媒体服务器成功->282 2024-05-17 16:47:04,681 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.681 I MediaServer[282-MediaServer] System.cpp:135 systemSetup | core文件大小设置为:18446744073709551615 2024-05-17 16:47:04,681 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.681 I MediaServer[282-MediaServer] System.cpp:144 systemSetup | 文件最大描述符个数设置为:1048576 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.681 D MediaServer[282-stamp thread] util.cpp:364 operator() | Stamp thread started! 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] EventPoller.cpp:460 EventPollerPool | 创建EventPoller个数:6 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:554 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:1935 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:80 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:443 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:9000 2024-05-17 16:47:04,683 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.682 I MediaServer[282-MediaServer] TcpServer.cpp:199 start_l | TCP Server listening on [::]:10000 2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] UdpServer.cpp:104 start_l | UDP Server bind to [::]:10000 2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] UdpServer.cpp:104 start_l | UDP Server bind to [::]:9000 2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] main.cpp:361 start_main | 已启动http api 接口 2024-05-17 16:47:04,684 [41] DEBUG AKStream - [AKStreamKeeper]->[ZLMediaKit]->2024-05-17 16:47:04.683 I MediaServer[282-MediaServer] main.cpp:363 start_main | 已启动http hook 接口 2024-05-17 16:47:05,373 [41] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(466) 2024-05-17 16:47:06,373 [41] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(467) 2024-05-17 16:47:07,372 [41] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(468) 2024-05-17 16:47:08,374 [29] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(469) 2024-05-17 16:47:09,373 [33] DEBUG AKStream - [AKStreamKeeper]->Common.OnTimedEvent运行中...(470)
> 
> 配置文件 AKStreamKeeper/Config/AKStreamKeeper.json { "IpV4Address": "127.0.0.1", "IpV6Address": "fe80::8:807:2143:28a1%5", "Candidate":"127.0.0.1", "WebApiPort": 6880, "MediaServerPath": "/opt/media/MediaServer", "AkStreamWebRegisterUrl": "http://172.17.0.1:5800/MediaServer/WebHook/MediaServerKeepAlive", "CutMergeFilePath": "/Users/qiuzhouwei/Downloads/CutMergeFile", "CustomRecordPathList": [ "/Users/qiuzhouwei/Downloads" ], "UseSsl": false, "MinRtpPort": 10001, "MaxRtpPort": 20000, "MinSendRtpPort": 20002, "MaxSendRtpPort": 20200, "RandomPort": false, "FFmpegPath": "/usr/bin/ffmpeg", "AccessKey": "047I4WS1-U51UBO6W-1J4BT21P-MF17IT99-92J8WIHU-944Q4KIW", "RtpPortCdTime": 3600, "HttpClientTimeoutSec": 5, "DisableShell": false, "CheckLinuxDiskMount": false, "ZLMediakitSSLFilePath": "./sslfiles/", "ListenIp": "0.0.0.0", "EnableRtspAuth": true }
> 
> 配置文件 AKStreamWeb/Config/AKStreamWeb.json
> 
> { "MediaServerFirstToRestart": true, "DbType": "MySql", "OrmConnStr": "Data Source=172.17.0.1;Port=3306;User ID=root;Password=pianote; Initial Catalog=akstream;Charset=utf8; SslMode=none;Min pool size=1;", "WebApiPort": 5800, "AccessKey": "047I4WS1-U51UBO6W-1J4BT21P-MF17IT99-92J8WIHU-944Q4KIW", "HttpClientTimeoutSec": 5, "WaitEventTimeOutMSec" : 10000, "WaitSipRequestTimeOutMSec" : 5000, "DeletedRecordsExpiredDays" : 30, "EnableGB28181Server": true, "EnableGB28181Client": false, "ZlmFlvPrefix" : "live", "ListenIp": "0.0.0.0", "ForwardUnmanagedRtmpRtspRtcStream": false, "LocalizationKingBaseDb": false, "ForwardUrlIn": "http://", "ForwardUrlOut": "http://", "ForwardUrlOnRecord": "http://", "PushStreamIpGetUrl": "" }

你解决了吗？我用deploy部署AKStreamKeeper一样的问题，json反序列化报错。
