### ISSUE TITLE
dotnet /root/AKStreamKeeper/AKStreamKeeper 执行报错提示权限不足

### ISSUE THREAD

**Issue by runtudecha** [chatop2020/AKStream#88]
环境  ubuntu24.04
步骤：执行
到执行这一步发现权限不够的问题，全程都是使用root执行的 ，请问是什么原因

sudo dotnet /root/AKStreamKeeper/AKStreamKeeper.dll
Unhandled exception. System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_TotalSize()
   at LibSystemInfo.DiskInfoValue.GetDrivesInfo() in /root/AKStream/LibSystemInfo/DiskInfoValue.cs:line 20
   at LibSystemInfo.SystemInfo.GetInfo() in /root/AKStream/LibSystemInfo/SystemInfo.cs:line 95
   at System.Threading.Thread.StartCallback()

**Comment by chatop2020** [comment]
系统层面报出来的权限不足，要不是系统有限制要不就是配置有问题，你要自己查一下
